name: Deploy Backend a EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Se obtiene una copia del repositorio para ejecutar las acciones
      - name: Checkout del código
        uses: actions/checkout@v3

      # Se configuran las credenciales de AWS utilizando los secretos de GitHub
      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # Se autentica el entorno de GitHub Actions con Amazon ECR
      - name: Login a Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Se construye la imagen Docker del backend y se envía al repositorio ECR
      - name: Build, tag y push de la imagen a ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: backend-actividad
          IMAGE_TAG: eks-v1
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # Se actualiza la configuración de Kubernetes para conectar con el clúster
      - name: Actualizar Kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name proyectoeks

      # Se genera el manifiesto del secreto dinámicamente y se despliega la infraestructura
      - name: Desplegar infraestructura en EKS
        run: |
          cat <<EOF > k8s/mysql-secret.yaml
          apiVersion: v1
          kind: Secret
          metadata:
            name: mysql-secret
            namespace: tienda
          type: Opaque
          data:
            MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          EOF
          
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/mysql-secret.yaml
          kubectl apply -f k8s/mysql-deployment.yaml
          kubectl apply -f k8s/mysql-service.yaml
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml
          kubectl apply -f k8s/backend-hpa.yaml